#!/bin/sh
# debian-live-build auto/config for YasserOS amd64 VirtualBox testing image
set -e

lb config noauto \
    --mode debian \
    --system live \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloaders grub-efi \
    --debian-installer none \
    --memtest none \
    --iso-application "YasserOS" \
    --iso-publisher "YASSERRMD" \
    --iso-volume "YasserOS-amd64" \
    --firmware-binary true \
    --firmware-chroot true \
    "${@}"
