[greeter]
background=/usr/share/yasseros/wallpapers/yasseros-default.svg
theme-name=Greybird-dark
icon-theme-name=Papirus-Dark
font-name=Cantarell 11
xft-hintstyle=slight
clock-format=%H:%M  %a %d %b
show-clock=true
position=50%,center 50%,center
panel-position=bottom
indicators=~host;~spacer;~clock;~spacer;~power
