[greeter]
background=/usr/share/yasseros/wallpapers/yasseros-default-1920.png
theme-name=Greybird-dark
icon-theme-name=Papirus-Dark
font-name=Noto Sans 11
xft-hintstyle=slight
clock-format=%H:%M
show-clock=true
position=50%,center 50%,center
